version: '3.8'
services:
  db:
    image: mysql
    container_name: mysql-dev
    restart: always
    command: --default-authentication-plugin=caching_sha2_password
    networks:
      - my-network
    env_file: .env
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      # So you don't have to use root, but you can if you like
      MYSQL_USER: ${MYSQL_USER}
      # You can use whatever password you like
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      # Password for root access
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - mysql-data:/var/lib/mysql
# Names our volume
volumes:
  mysql-data:
networks:
  my-network:
    driver: bridge
    external: true

